# Generated by Django 4.1.2 on 2022-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_song_artiste_song_artiste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateField(auto_now_add=True),
        ),
    ]
